### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [JoniVanderheijden/prezto-last-working-dir#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by JoniVanderheijden** [comment]
Oh, that was unexpected. This is mostly the oh-my-zsh version with some minor adjustements so I'll have to have a look at what their restrictions are. You might like this one better, it has a license and is a bit more generic, as in the cache directory isn't set specifically to prezto folders: https://github.com/mdumitru/last-working-dir

**Comment by JoniVanderheijden** [comment]
I added the MIT license from oh-my-zsh, I should have done that when copying the plugin code anyway. Thanks for pointing that out.
